# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.13" do
  version "0.0.13"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "45f632b105902aa088c48a2e558f6735ca2c6f2940949a1e8b4503f327e13503"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "f53b20326b60b98ced41d654c69123ea1279d1a0c1fb8e8687bffed2e22d7f90"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "43be26606002881a982555c6c67df65cfb1b112630c8d9ab30ee093ce5ae8202"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "6b4b922aa4c6b3dd915c419287774d522e8bbb627cab38ce1652dbd2affbb653"
    end
  end

  name "nitro@0.0.13"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
