# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "4170017760af92b6be10d4bd1af5289b669ec9620378e74e342fe5f7ed1fd00a"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "e93df122648b9f1fc6dcc5fc9af722179a6e7efa854af1a5cc1353fb7cf626fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "bfad375ddfd184955f51c069ae142f809abce668c7aae5fb98470792a7395d8c"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "bae4e5a766a541917624be90d13b459963a2e75bc968bdffac6964a41cec4489"
    end
  end

  name "nitro@0"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
