# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.6" do
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "3f11919c200ec6a04364ac575dc0544df1903aad59268d6a89668f01bcb37dad"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "2b740de9a8ed94b3803321323148bac2fadca173a27717aec5d41d6d5cdea008"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "560c9986ef4d64877cafc9d9e35e86bd5bd54c7a5cc7fe9b0c895f84f86cacff"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "773486cff6e74cfd407b18c8ee90545cf74b7d89a532ef80caea4e49ec5876c1"
    end
  end

  name "nitro@0.0.6"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
