# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro" do
  version "0.0.21"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "36385d061f23904f66f59fc2f0a71e5252707fb2d8b7a5c82e8ca7fcd2f34f04"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "daa13d44b0a92f09e8ce4e2ea9d282076493d485cd2778418e8800d997692425"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "e11dd5b97bcd837c09d725b9fe3ee69959cf6f269a6c34be53177b3f2ceacd1c"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "c29550e9d317f6d855e3aceef5a2f51081cc087db55a47c32a16f9c38b447b24"
    end
  end

  name "nitro"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
