# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.19" do
  version "0.0.19"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "79fec0c5bae896157eebc925fbbbfe780cff3940fee6428351f5b784eae1fef7"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "9012d851d83c5b7afd33406e179dc657016cfbb1b402d99312b2c121e6b839d2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "73e0496c1e27f97c65b1ed63c452da829c9b1c4dff4c46a4a0f90ae82f26626e"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "c71aa1c10f5610ad7ba4cefa46dde43a25477fe14a187d7631119075a6254aa4"
    end
  end

  name "nitro@0.0.19"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
