# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro" do
  version "0.0.16"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "dc51b64222700e0161f0e1a4824687dfd2ece39a86efd5b1253bdfddba3c5f4d"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "7733581b36a315a6f0febe2a9a62b7400011bf8d3ea5e4c7880f87afbe0c26d2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "a6cca656cdb9f67cb66862471dcdd46be4043de8fa697f53d9e576bf1bf73efe"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "e48ff8db8731716253ad700f0403a308771abdc8ef46f9f6b9f1d743079bcc17"
    end
  end

  name "nitro"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
