# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.24" do
  version "0.0.24"

  on_macos do
    on_intel do
      sha256 "3d949a4bf6bb6bf3f5d90363c4dec5cdb06462a2a6d60dfb857a7ae61e1cc376"
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
    end
    on_arm do
      sha256 "85cfbd020f9e2f7a5443143a2bfbe547adfeb9f57a898adf24dc1e4317fa5cb9"
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "445454eb90922cdd90c5348265a5c0d3de8b9714e692f225c26052fb844e935b"
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
    end
    on_arm do
      sha256 "fa5bffcb92ad56a7910afa69ca79c3b62307241bd31b529b89ddafd34342e87f"
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
    end
  end

  name "nitro@0.0.24"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
