# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.14" do
  version "0.0.14"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "737ca6ff14eaa05caa7f92c7f428fd60438c38f6efad30735c13aec04f1454f9"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "a7ac750d8798e0e4ad8cfdc6d8b2c7d5b8b76af6f9144f2fdc13f291d9263e58"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "08588503ae4289effbee460a52e6ddcd9a4c10a6ea2fae808c4997b2208cc434"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "2b1ce657c03c3fd62a5041ca9745ec0fd912be55cd09cd8d81c4d802f73a80a2"
    end
  end

  name "nitro@0.0.14"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
