# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.9" do
  version "0.0.9"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "17c60372c39036ac5cd8d65854d693faba34475c6668aeb54c45061794201679"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "f5807b4064603ab3db06316cd0183cdfb3602e738ede1cbfa961f663c8206dee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "b58bc899906efc9a2f7cec5a2545c010728457e3c050d2a4d59012cba8296fda"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "345ee2a80a7f7332249e54c3d36523b37f0a4f90baa8e2b514b7cd0076cbf215"
    end
  end

  name "nitro@0.0.9"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
