# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.1" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "4e252c6ea907fc19247d527833f81f3403630fbbef7d98ebe565f4ea19b01c3e"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "a58d595b9896fce4a36a8237cb295b691481c2aed223254e31826ee7cac04742"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "e1c0f16e36e4c96976a5f45eed8cab690371c370dc48496edc3d4eb945391a06"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "8be834dc9cc16c1c9ee1e6b1318c0a323e7071c01102ca228ed5d1e159c70122"
    end
  end

  name "nitro@0.0.1"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
