# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.5" do
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "81fa0a61fbf9b6397b8c36d1122d866e3b9f07e60ef5167e2f0cb5f2bcc4b12f"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "d8f502db09888f9e17e33ee6f356c7a1ba7605d0dd5725391d540e4c84b3e71d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "5060ec10477179f031d7e6d28fc5badaa8ed349416deb50f7a535b5cd16df1a0"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "7e8021b79c4f79fe11f1e1c51ddb9d9e6a83346693ffefce6561ae9ad42338ea"
    end
  end

  name "nitro@0.0.5"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
