# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.15" do
  version "0.0.15"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "bff4cc7bdb0ca558d060347dac0286ca46161b293d70ecfed20525fe9014e0ce"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "5379f1e98e5d6aaf9bd98461438834a6010c6b8cbaa8a0c839161ceed2cdb004"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "00e99a70774b17ee31d4d38c970058c4b69bcbf962a325a7bf2ca1048fd9ac8d"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "5f5bbf6283598f07c1cb912b4710e96aa08c02209c9e082354939fa83cd5b3ab"
    end
  end

  name "nitro@0.0.15"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
