# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0" do
  version "0.0.11"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "c71b377fa59f9da4ad42211e80f9bb61ceb87ab3245c2f1f0e9aed95f88c3f68"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "b628595b6d11eba7032ed0c06d9bb61718abddf0f8d2bc96e644d6f183333cfa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "c0e3b4188bb38fc16c9e9590b6c6cbee44f748b0cbffd9e33ec675cd6d91bdd0"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "cc6cb33828d792753ccd13174749d53c330e517dfcfb174b6d7193e0f7d55b19"
    end
  end

  name "nitro@0"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
