# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.12" do
  version "0.0.12"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "63b6a4f2542e03ea1479b3d1dba99980fd001efaa40e6f9955fbbfa0131899ef"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "1aeab2e15508379b2aaa640cff55383768795a9a2d6c53fb933dd1b37a2ef57f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "2de34beeee24151d84e1ac1a3aa293f53de3f71af450bdbdf759ed1fe6373fac"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "aee95fcab04879bf81c1ee81e30c21a399d327b167baf9a41dd1a61e56ab5b3d"
    end
  end

  name "nitro@0.0.12"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
