# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0" do
  version "0.0.8"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "3adcb37d907ec941cef51796506628893341604efabf72725bd56f30ac587cb3"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "e8b2100ec2005fe397b489b70cfb95c5c9e1d4e65a8bae74059c3652b1c38521"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "2bdf40ad1975edfa36fe34aff0db5ead17e894043ee165d31ea5576861a7ce3e"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "c16717aaed7052879259c22abc1d74b4d36aaf07e11a6c4ee5e8996cc54d4df2"
    end
  end

  name "nitro@0"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
