# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro@0.0.2" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "2b62ac304c24cd247d2eeb7933de6f7e87560175e70063ed754e156ab9c6dd52"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "b18161510855f8b35c834c06c702c98830a15df1b3ccd313d87ff1ac6f8eb562"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "2a103d717e2b687b62e0064557d82f2c7f1f4bc1b128f328d71a9b0ac5d4be5b"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "507293aa1433c2785bff4fff14d60edcfc01c840eed39c2e529c6ac8673f26e7"
    end
  end

  name "nitro@0.0.2"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
