# This file was generated by GoReleaser. DO NOT EDIT.
cask "nitro" do
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "f3569889b404cdbfaf540e0075e24e9f4ab500657813a707808a8e5cce3fc27d"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Darwin_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "65aef0f21fc1c0bbc01ec23c262b21f6a996528c16bcb83692e57e2014015c3c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_x86_64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "8647239601911ac22871baa17770ee254fdae45af76493b1c21e9b8316e92c40"
    end
    on_arm do
      url "https://github.com/nitroagility/nitrocli/releases/download/v#{version}/nitrocli_Linux_arm64.tar.gz",
        verified: "github.com/nitroagility/nitrocli/"
      sha256 "ab7cea1d6c1102dda338338f2864668445748d511cd28f158200688041fd5ecc"
    end
  end

  name "nitro"
  desc "NitroCLI - The official CLI for NitroAgility"
  homepage "https://www.nitroagility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nitro"

  # No zap stanza required

end
